[package]
name = 'four_bit_adder'
version = '0.1.0'
description = 'A four bit adder'
author = 'Naren Dasan'
license = 'NCSA'

[repository]
url = 'https://github.com/veritas-verilog/four_bit_adder'
version_control = 'git'

[dependencies]
"veritas-verilog/full_adder" = "0.1.0"
